### ISSUE TITLE
override whole branch in merge if value provided in second one

### ISSUE THREAD

**Issue by fizyk** [pylover/pymlconf#7]
Hey, I though it worked that way, but apparently I'm missing something, so firstly, let me ask if that makes sense:

We have two configs:

``` yaml

key:
   subkey:
       another1: value
       another2: value
   subkey2: value
```

and

``` yaml

key:
    subkey: false
```

So, my proposition, is to be able to merge these two like:

``` yaml

key:
    subkey: false
    subkey2: value
```

So, the merge would have to be able to override in this case completely with value, and do not follow further the original ConfigDict tree
